server:
  port: 8080

mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath*:*.xml
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 2
    timeout: 2000
    thymeleaf:
      cache: true
      prefix: classpath:/templates/
      check-template-location: true
      suffix: html
      encoding: UTF-8
      content-type: text/html
      mode: LEGACYHTML5