server:
  port: 8080

mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath*:*.xml
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    #password: online_education 本地不适用密码
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
    timeout: 0







#spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    check-template-location: true
#    suffix: html
#    encoding: UTF-8
#    content-type: text/html
#    mode: HTML5
#spring:
#  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/view/

